changelogs:
  - version: 0.1.17
    date: 2022年12月14日
    changes:
      - 新增配置项 `ingress-url-format`
  - version: 0.1.18
    date: 2024年01月02日
    changes:
      - RBAC 权限收敛
      - 更新模版和配置参数
      - 增加中文 README
  - version: 1.1.28
    date: 2024年01月08日
    changes:
      - 变更同 `v0.1.18`, 覆盖旧的 `v1.1.28` 版本
  - version: 1.1.29
    date: 2024年02月01日
    changes:
      - "支持在 SparkApplication 中添加 `scheduling.x-k8s.io/suspend: \"true\"` 注解实现 suspend 操作，从而允许 kube-queue 进行排队处理"
  - version: 1.1.30
    date: 2024年04月08日
    changes:
      - 修复 RBAC 权限导致作业提交失败的问题
  - version: 1.1.31
    date: 2024年07月31日
    changes:
      - 修复 webhook 与 operator pod 标签不匹配的问题
  - version: 2.0.0
    date: 2024年09月23日
    changes:
      - 同步 [kubeflow/spark-operator](https://github.com/kubeflow/spark-operator) 2.0.0 版本
