apiVersion: v1
kind: ConfigMap
metadata:
  name: dummy-cm
  namespace: default

---
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi-configmap
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: registry.aliyuncs.com/acs/spark:ack-2.4.5-latest
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: local:///opt/spark/examples/jars/spark-examples_2.11-2.4.5.jar
  sparkVersion: "2.4.5"
  restartPolicy:
    type: Never
  volumes:
  - name: config-vol
    configMap:
      name: dummy-cm
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 2.4.5
    serviceAccount: spark
    volumeMounts:
    - name: config-vol
      mountPath: /opt/spark/mycm
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.5
    volumeMounts:
    - name: config-vol
      mountPath: /opt/spark/mycm
